### ISSUE TITLE
Minicart on product pages - .breakdance-woocommerce class causing width: 100%

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#284] opened 2022-08-26 13:13 UTC
In beta 10 the header gets misformed on the product page.

Its because the .breakdance-woocommerce class is added to .bde-mini-cart and on the product page it gets width=100%

**Comment by FelipeMarcos** [comment] 2022-08-29 16:22
@mikehenze, I couldn't reproduce this. 

- Do you have a screenshot for us?
- Does it happen for the Single Product page or the Shop/Product Archive Page?
- Does it still happen on the recent beta 11?

**Comment by mikehenze** [comment] 2022-08-29 16:56
- Please see https://www.internet360.nl/jilsen/product/melanie-suede/
- Single product page
- Yes beta 11 also

**Comment by FelipeMarcos** [comment] 2022-08-29 17:06
Thanks, I've managed to reproduce the issue. This should be fixed in the next beta.

**Comment by mikehenze** [comment] 2022-09-01 07:08
This seems fixed in beta 12, thanks

**Closed** 2022-10-31 18:00 UTC
Labels: assigned
