### ISSUE TITLE
1.0.1 RC 1 - WP Menu - Mobile Menu > "Right" position doesn't work on the front-end.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#421] opened 2022-09-23 15:04 UTC
Steps:

1. Add a WP Menu element
2. Set it to swap to mobile menu at Tablet Landscape
3. Set the mobile menu to off-canvas
4. Set off-canvas position to "right"

It works as expected in the builder, but on the front-end the menu is still positioned on the left side of the viewport instead of the right.

**Comment by a-dubiel** [comment] 2022-11-28 18:30
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.

**Closed by a-dubiel** 2022-11-28 18:30 UTC

**Comment by a-dubiel** [comment] 2022-12-13 14:14
Hey @mikehenze - I still can't reproduce it. 

Please e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials. Also please mention the fact you have this CSS fix in place.
