### ISSUE TITLE
Repeated ID's for the Search Element

### ISSUE THREAD

**Issue by maxproway** [soflyy/breakdance-bugs#832] opened 2023-06-07 14:02 UTC
Search element has repeated ID's, as a result Google Pagespeed decreases accessibility rank:

![image](https://github.com/soflyy/breakdance-bugs/assets/98363451/1f94ceaa-32e9-4ea7-b418-9afb418f355c)

**Comment by louisreingold** [comment] 2023-11-02 04:18
This is solved in Breakdance 1.6. Thanks for the report.

**Comment by louisreingold** [comment] 2024-01-10 05:03
This is apparently back in 1.7.

**Comment by GregorTr** [comment] 2024-03-07 09:55
At the moment ``%%ID%%`` will not be unique if an element that uses this is output through a global block by the Repeater field.
``%%ID%%`` apparently isn't affected through ``$repeaterItemNodeId`` the same way as ``%%SELECTOR%%`` is? Is this intentional?

**Comment by breakdancemoderator** [comment] 2024-07-17 11:00
@maxproway Thanks for the report. This has been addressed in 2.0.

@GregorTr Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.

**Closed by breakdancemoderator** 2024-07-17 11:00 UTC
Labels: :bug: bug
