### ISSUE TITLE
Menu Builder Custom Dropdown - responsive issues

### ISSUE THREAD

**Issue by bluefish1960** [soflyy/breakdance-bugs#68] opened 2022-07-05 10:38 UTC
Hi, I have been adding stuff to the custom menu dropdown to make a row of 4 columns. The dropdown has a wrapper div added inside and then an inner div to hold the elements which are an image and heading. The desptop view look pretty nice but any breakpoints the whole thing falls apart because if I change the setting to display as a column or decrease the image size, then all the breakpoints change too.
It is very early days - the pages I am working on are https://main.ajm7.uk/ and https://main.ajm7.uk/shop/ and the custom menu is on the about link
On the first link the container does not align centered even though it does center properly in the builder.

**Comment by louisreingold** [comment] 2022-07-13 01:26
Closing because this is not reproducible and the page leads to a 404. Your support team is happy to take a look if you email support@breakdance.com.

**Closed** 2022-07-13 01:26 UTC
