### ISSUE TITLE
Shadow not extending past edge of div

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#527] opened 2022-11-10 15:21 UTC
I've added a shadow to a div, the page has 10px padding so that the elements aren't right up against the edge of the screen but the shadow doesn't extend past the div so looks ugly on mobile where it hits the edge of the div and suddenly stops, as you can see in the screenshot attached. 

Not sure if this is a css limitation or something that can be resolved?

![shadow-problem](https://user-images.githubusercontent.com/117674105/201134260-4e58f91c-6d00-4c15-981e-673fc348fa59.JPG)

**Comment by a-dubiel** [comment] 2022-11-11 07:24
Please provide exact steps to reproduce this issue. From what I see there is `overflow: hidden` set somewhere. Perhaps on the wrapper element.

**Comment by LambMediaGroup** [comment] 2022-11-11 10:03
I've created a section that has the default 20px padding on either side and in there I've added an advanced tab element.

Inside one of the tabs I have a bunch of divs set to 20% width on desktop and 25% on tablet etc etc down to 100% on mobile. When on desktop, tablet H and tablet V it works fine but once down to mobile H and Mobile V you then get the weird shadow cut off.

I've attached a screencast of me resizing the browser window so you can see where it goes wrong.

[Video](https://www.staging6.whichgreekisland.co.uk/wp-content/uploads/2022/11/screen-capture-3.webm)

**Comment by LambMediaGroup** [comment] 2022-11-22 14:53
I've found that there's css created for the advanced tabs that's causing it, on my test site this is what's created. If I remove the overflow hidden from the dev tools then the shadow works.

@media (max-width: 767px)
.breakdance .bde-advanced-tabs-18-104 {
    flex-direction: column;
    align-items: unset;
    **overflow: hidden;**

**Comment by a-dubiel** [comment] 2022-11-22 15:02
This is super helpful. I am addressing this as we speak and looks like this will be fixed with the next release.

**Comment by a-dubiel** [comment] 2022-11-29 12:45
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.

**Closed by a-dubiel** 2022-11-29 12:45 UTC
Labels: :bug: bug, :rocket:    planned
