### ISSUE TITLE
Advanced Slider - setting slides per page to more than 1 breaks infinite scroll.

### ISSUE THREAD

**Issue by udoro** [soflyy/breakdance-bugs#778] opened 2023-04-11 23:21 UTC
Infinite scroll won't work if the number of slides per view is more than one.

Breakdance Version 1.3 Alpha 1

I haven't tested this on previous versions.

**Comment by a-dubiel** [comment] 2023-04-12 15:22
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/721

**Closed by a-dubiel** 2023-04-12 15:22 UTC
