### ISSUE TITLE
Zero theme removes normalize.css?

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#986] opened 2023-11-02 21:42 UTC
https://www.facebook.com/groups/breakdanceofficial/posts/6762826897085881/

**Comment by bouveng** [comment] 2023-11-02 23:10
Thanks @louisreingold !

Also, I know you guys have a lot of tricks up in your wizard sleeve, but why is the `Template:` section of zero theme missing?

Br.

**Comment by breakdancemoderator** [comment] 2024-05-27 23:54
normalize.css was present during our tests. Closing.

**Closed by breakdancemoderator** 2024-05-27 23:54 UTC
Labels: :crossed_fingers: unconfirmed

**Comment by xDESOLx** [comment] 2025-02-07 18:53
I'm having the same issue, after installing and enabling the Breakdance Zero Theme and setting Breakdance to use the active theme instead of disabling the theme system the normalize.css stops loading which results in margins around <body> tag and some other inconsistencies. It's weird as the Zero Theme available on GitHub is the same theme that WordPress recognizes when Breakdance disables the theme system (the files can be inspected with the Theme File Editor tool in WordPress) so I would expect it to behave exactly the same as if I were to disable the theme system in Breakdance options.

**Comment by xDESOLx** [comment] 2025-02-10 12:11
Okay so after examining the source code of Breakdance I see where the issue is - Breakdance checks the active theme by title and loads the normalize.css only when the active theme (or parent theme) is named "Breakdance Zero Theme". This is an issue when someone tries to make a Zero Theme lookalike with a different title. Installing the Zero Theme and then making a child theme solves the issue.
