### ISSUE TITLE
Custom field as image source

### ISSUE THREAD

**Issue by jorodr** [soflyy/breakdance-bugs#219] opened 2022-08-13 05:39 UTC
Hello,

I don't think custom field work as image source. Cannot make it working. Neither the field return URL, neither ID of an image.
I hope it will be improved.

Best regards,
George

**Comment by louisreingold** [comment] 2022-08-16 01:13
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/193

**Closed by louisreingold** 2022-08-16 01:13 UTC
