### ISSUE TITLE
Dynamically set section background - not showing in editor on tablet view and below.

### ISSUE THREAD

**Issue by nicolanugon** [soflyy/breakdance-bugs#256] opened 2022-08-21 08:53 UTC
The section background image does not display when working in the editor. Only in responsive mode. Works fine on the front-end. It only happens when the background is dynamic (featured image)

![image](https://user-images.githubusercontent.com/51177627/185783451-44e2473a-9a59-4de6-bb9a-dcca113256d3.png)

**Comment by louisreingold** [comment] 2022-08-27 21:23
I can't reproduce. Can you send me a GitHub Gist with the copy/paste of your element? 

https://www.loom.com/share/f224921dc23a418c9a8bc37c9f8b3f0a

**Comment by Dancerist** [comment] 2022-08-27 23:56
I see where the problem is. It only happens when the background is dynamic (featured image)

**Comment by a-dubiel** [comment] 2022-10-31 18:04
This has been fixed in the latest 1.1 Beta

**Closed by a-dubiel** 2022-10-31 18:04 UTC
Labels: assigned
