### ISSUE TITLE
Breakdance breaks wordpress

### ISSUE THREAD

**Issue by basecrest** [soflyy/breakdance-bugs#37] opened 2022-06-27 10:31 UTC
Once Breakdance Alpha 2 installed and activated. I began by checkout out the menu. Firstly i went to themes and got the first screenshot saying 'Internal server error'. Then when i proceeded to check out the other menu pages the whole wordpress site collapsed and revealed this one page that says 'There has been a critical error on this website. Please check your site admin email inbox for instructions'. I did check my email but no instructions are sent to email. The scary thing was this page was constant and i could not log out or login. Then a basic wordpress dashboard page appeared the home page / url (screenshot attached) and I managed to deactivate Breakdance. Wordpress now working as intended.

<img width="1296" alt="Screenshot 2022-06-26 at 00 03 38" src="https://user-images.githubusercontent.com/8845093/175921580-10a34ee9-822d-4216-b453-ad2f18116738.png">
<img width="1032" alt="Screenshot 2022-06-26 at 00 04 02" src="https://user-images.githubusercontent.com/8845093/175921592-bda4ff9c-4d24-410c-8ec5-aaad47f1b78e.png">
<img width="1105" alt="Screenshot 2022-06-26 at 00 12 36" src="https://user-images.githubusercontent.com/8845093/175921598-5ac34a1c-3c71-4b03-8200-002eec0161ba.png">

**Comment by basecrest** [comment] 2022-06-27 12:29
Update:

I had not activated the domain on breakdance site prior to adding license key in wordpress. Hope this is the issue. I've installed Breakdance on another domain and its working just fine.

**Comment by louisreingold** [comment] 2022-07-19 06:07
Closing as unable to reproduce. If anyone reading encounters this problem or similar problems, submit a support ticket with your WP admin login details: https://breakdance.com/support/

**Closed** 2022-07-19 06:07 UTC
