### ISSUE TITLE
Columns Element missing "Never" option in Layout > Force Vertical Stacking

### ISSUE THREAD

**Issue by nick-s5** [soflyy/breakdance-bugs#27] opened 2022-06-26 22:06 UTC
1. Add a columns element
2. Go to it's Layout tab
3. Force Vertical Stacking is missing a "Never" option

Adds just a little unnecessary headache for things like mobile headers where you want the logo on the left and the menu button on the right. Have to build it from the beginning with divs instead of using the Columns element.

**Comment by neeckola** [comment] 2022-06-29 03:52
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/30

**Comment by louisreingold** [comment] 2022-07-19 06:05
We added a "Never" option in Beta 1.

**Closed by louisreingold** 2022-07-19 06:05 UTC
