### ISSUE TITLE
ACF WYSIWYG custom field - paragraphs / spacing not respected

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#228] opened 2022-08-13 15:50 UTC
I am using a custom field called Features which is a WYSIWYG custom field. When I added the text the content doesn't respect the paragraphs or the space. 

I tried to use the rich text element and the basic text element and neither of them work. 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7070435/184501373-e5656fdf-67fa-42dd-9bfc-53a3cc427ab0.png">

**Comment by louisreingold** [comment] 2022-08-17 03:39
I can't reproduce this. I linked a Text element to a WYSIWYG Editor ACF field and my text displayed with the exact same HTML tags/formatting as it did in the ACF editor.

Please send WP admin login details to support@breakdance.com.

**Comment by misslaidlaw** [comment] 2022-08-17 22:24
Okay this was me using the Pods Custom Fields, but there is no integration for that yet. The rest of the fields though seem to work. Just not this one.

**Comment by louisreingold** [comment] 2022-08-17 22:27
OK, closing and linking to this in the Pods request thread in Canny.

**Closed by louisreingold** 2022-08-17 22:27 UTC
