### ISSUE TITLE
Condition is lost in pagination page > 1

### ISSUE THREAD

**Issue by jonasostrom** [soflyy/breakdance-bugs#603] opened 2022-12-05 15:16 UTC
Hi,

I have a condition to show a play-button if the post in a Post Loop has a category. It works but the paginated items is not working. They seems to not catch the condition or the condition is lost along the way.

This is build with a global block used in post loop element placed on a page.

<img width="1761" alt="Skärmavbild 2022-12-05 kl  16 07 13" src="https://user-images.githubusercontent.com/4511851/205672923-7361569e-b9b9-48f7-96a0-db11e492e88d.png">

<img width="2031" alt="Skärmavbild 2022-12-05 kl  16 10 34" src="https://user-images.githubusercontent.com/4511851/205672914-9627151f-44c9-4f15-898b-bd65fd000fc5.png">

**Comment by a-dubiel** [comment] 2022-12-05 15:59
@jonasostrom I cannot reproduce this. Just from looking at your code, you probably need to pass  post `ID` instead of `$post` object. This might work `has_category('travel-episodes', $post->ID)`. Not sure.

Closing this for now. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Closed by a-dubiel** 2022-12-05 15:59 UTC
Labels: :bug: bug, :crossed_fingers: unconfirmed
