### ISSUE TITLE
Dual Heading Element

### ISSUE THREAD

**Issue by nicolaskid** [soflyy/breakdance-bugs#43] opened 2022-06-28 02:05 UTC
In my hero section, the highlighted text background is bit off to left (see 1st img) at first visit of the page. but once refresh, it goes back to normal state (see 2nd img). However will comback after a hard refresh.

![290545953_5136938636403299_8507918594692099108_n](https://user-images.githubusercontent.com/51177627/176074432-2d758dff-9993-46b4-9257-0d3767d3d977.jpg)
![290640941_5136938956403267_161651018024199584_n](https://user-images.githubusercontent.com/51177627/176074453-7507dd4d-4a5a-48cd-af93-d164455ff056.jpg)

**Comment by neeckola** [comment] 2022-06-29 03:54
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/29

**Comment by louisreingold** [comment] 2022-07-04 03:46
Closing as duplicate of https://github.com/soflyy/breakdance-bugs/issues/29

**Closed by louisreingold** 2022-07-04 03:46 UTC
