### ISSUE TITLE
Issue with Post List on PHP 8.1 in 1.6 Beta 1

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#951] opened 2023-09-27 14:19 UTC
When using the post list element and making it a slider, I get an error.  Here's the automated message I get.

Error Code: 500
Request Time: Wed, 27 Sep 2023 14:13:49 GMT
Request URI: https://example.com/?_breakdance_doing_ajax=yes&_ajax_nonce=a304893306
Request Type: POST

To test, I deactivated every single other plugin except BD.  I downgraded to PHP 7.4 and didn't get this error using BD 1.6.  I then upgraded back to PHP 8.1 using BD 1.6 and the error returned. I then downgraded Breakdance to 1.5 using PHP 8.1 and did not get the error.  This means it must be something in BD 1.6.

What's interesting to me is that the new error message thing implemented in 1.6 implies that this is a server error.  As I mentioned above though, this is not an error that appears in BD 1.5.  Seems a little misleading to just imply it's a server error.

**Comment by thekendog** [comment] 2023-09-27 14:37
Error seems to be coming from line 263 of ssr.php in the PostsList folder.

**Comment by rodolphebertozzo** [comment] 2023-09-28 18:38
+1 when I would edit a post template single

**Comment by 00x1a** [comment] 2023-10-04 12:18
I can confirm. Post loop builder and Postlist create 500 error.

**Comment by louisreingold** [comment] 2023-10-12 04:42
@thekendog thanks for the report. The originally reported issue was fixed in https://breakdance.com/breakdance-1-6-rc-1/

@00x1a @rodolphebertozzo thanks also for your reports. I investigated your reports, but there is no guarantee we fixed your specific problem since you didn't provide an error message. **If you encounter further PHP errors, please do what the @thekendog did and provide the actual error message.**

**Closed by louisreingold** 2023-10-12 04:42 UTC
Labels: :crossed_fingers: unconfirmed
