### ISSUE TITLE
Drop-down menu icons (e.g. chevron) don't seem to appear

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#479] opened 2022-10-26 17:00 UTC
Kinda says it all...

**Comment by a-dubiel** [comment] 2022-10-27 09:44
Hey @digitalsmithy see https://github.com/soflyy/breakdance-bugs/issues/480#issuecomment-1293234156

**Comment by sherissar** [comment] 2022-11-22 13:40
Would be great if the drop-down arrow shows even where there is a link present in the top-level menu item. The drop-down arrow indicates there are sub-menu items. And the top-level menu can also be clicked.

**Comment by louisreingold** [comment] 2023-07-10 06:39
Closing as duplicate of https://github.com/soflyy/breakdance-bugs/issues/480, leaving the duplicate open.

**Closed by louisreingold** 2023-07-10 06:39 UTC
Labels: :gem: enhancement, :rocket:    planned
