### ISSUE TITLE
Bugged popup template page

### ISSUE THREAD

**Issue by alemacielsilva** [soflyy/breakdance-bugs#268] opened 2022-08-23 21:15 UTC
I had already created a popup which is still working just fine. However, when I went to create a second popup, I was surprised by an error that said 'the popup was not created or was created but not saved'. And upon reloading the page, I noticed that the popup template I had created before (the first one) was also gone.

![image](https://user-images.githubusercontent.com/21241956/186266466-f546e08b-647a-412f-819d-cfd26987334b.png)

And now, although the first popup is still visible (image below), it is no longer working and I can't make any changes to it, as the template is gone.

![image](https://user-images.githubusercontent.com/21241956/186266717-6c17ee78-e597-49da-a9d7-2bb5bb8121e9.png)

After all that, I tried to create a new popup to replace the first one, but apparently I can't do that anymore. Location not available

![image](https://user-images.githubusercontent.com/21241956/186270434-5c88a88f-aa5b-4092-8a8d-1eade28f0f05.png)

**Comment by louisreingold** [comment] 2022-08-24 04:08
I'm not able to reproduce this, but it's definitely a bug in Breakdance and may be related to your server environment.

Please email support@breakdance.com with your WP admin login details and we'll take a look and release a fix.

**Comment by a-dubiel** [comment] 2022-10-31 18:07
This has been fixed in the latest 1.1 Beta. Thanks for the bug reprot.

**Closed by a-dubiel** 2022-10-31 18:07 UTC
Labels: assigned
