### ISSUE TITLE
Dynamic Link on Wrapper Link

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#229] opened 2022-08-13 16:14 UTC
When creating a wrapper link and I add a normal link to it, it works, but when I add a dynamic link it doesn't. 

When I hover over the link I can see it's returning the shortcode [breakdance_dynamic field = "home_url"] instead of the link.

![image](https://user-images.githubusercontent.com/7070435/184502156-d447ad10-5b4d-40ae-9938-aa54efaed1ce.png)

**Comment by mikehenze** [comment] 2022-08-13 18:33
Dupe of https://github.com/soflyy/breakdance-bugs/issues/221

**Comment by misslaidlaw** [comment] 2022-08-14 01:21
Oh thanks.

**Comment by louisreingold** [comment] 2022-08-15 10:31
It might be a separate issue so please leave this one open.

**Comment by djrwp** [comment] 2022-08-15 22:06
I'm seeing the same issue when using post permalink for wrapper it's showing /[breakdance_dynamic%20field='post_permalink'] in final url. If I use the same dynamic link for featured image or heading it works, just not with Wrapper link.

**Comment by louisreingold** [comment] 2022-08-15 23:44
Thanks for the report. I've fixed this and the fix will ship in beta 8.

**Closed by louisreingold** 2022-08-15 23:44 UTC
