### ISSUE TITLE
The Woocommerce minicart does not update with WP Rocket activated

### ISSUE THREAD

**Issue by lalucioledigitale** [soflyy/breakdance-bugs#878] opened 2023-06-30 08:16 UTC
Breakdance v1.3.1
Wordpress : 6.2.2
WP Rocket : 3.14
Woocommerce 7.8.1
Chrome, Safari
MacOS

**Reproduction  Steps**

Breakdance's Woocommerce minicart doesn't work properly when WP Rocket is activated, even though WP Rocket is supposed to take Woocommerce into account in its default configuration.
You can see this problem on this site by adding products to the basket and then navigating between pages:
https://tadelaktdesigns.com/boutique/

Thank you in advance for your feedback.

**Comment by louisreingold** [comment] 2023-07-09 23:33
There's also a known similar issue with the Mini Cart due to a recent WooCommerce update, but this will be addressed in Breakdance soon. I suspect that's what this is, and it's not actually WP Rocket.

However, if there is an alternate issue that actually is caused by WP Rocket, I'd recommend contacting the WP Rocket team.

**Closed by louisreingold** 2023-07-09 23:33 UTC
Labels: :crossed_fingers: unconfirmed

**Comment by lalucioledigitale** [comment] 2023-07-10 15:01
Hi Louis,
Thanks a lot for your feedback !
