### ISSUE TITLE
UI - Typography Preset Delete Button Invisible in Light Mode

### ISSUE THREAD

**Issue by kbcelik** [soflyy/breakdance-bugs#13] opened 2022-06-24 10:44 UTC
The delete button is not visible in the preset delete popup. defined in style with a white background.

![ss-preset](https://user-images.githubusercontent.com/52469338/175519113-572d80f3-4d55-44f9-8f7c-72d0249b5f8e.png)
![ss-preset-2](https://user-images.githubusercontent.com/52469338/175519301-4fdc22e2-b876-4471-9592-6a09ad21d251.png)
.

**Comment by louisreingold** [comment] 2022-08-01 02:34
I'm not able to reproduce this:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/6425257/182061233-976a18e9-33c7-45d0-bdaf-bf67136977f8.png">

It's possible it was fixed in beta 2/3/4/5, but if it still happens for you, please email support@breakdance.com with your WP admin login details and we'll take a look.

**Closed by louisreingold** 2022-08-01 02:34 UTC
