### ISSUE TITLE
error when adding the form builder to a page

### ISSUE THREAD

**Issue by emyerfo** [soflyy/breakdance-bugs#15] opened 2022-06-24 17:28 UTC
**CLEARLY and CONCISELY Describe the bug**
Error displayed when adding Form builder to a page (see image: https://take.ms/jo3KG)

**To Reproduce**
1. Go to 'any page'
2. Click on 'add form builder'

**Comment by neeckola** [comment] 2022-07-26 23:50
Couldn't reproduce, maybe fixed meanwhile?

**Comment by louisreingold** [comment] 2022-08-01 02:32
I'm not able to reproduce this. It's possible this was fixed in beta 2/3/4/5. If this still happens for you, please email support@breakdance.com with your WP admin login details and URL to a page where the problem takes place.

**Closed** 2022-08-01 02:32 UTC
