### ISSUE TITLE
Formbuilder Overflow Smartphone

### ISSUE THREAD

**Issue by codingharz** [soflyy/breakdance-bugs#806] opened 2023-05-17 09:16 UTC
**What version of Breakdance are you using?**
BD 1.3 Beta 2

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction Steps**
In the form builder, there is an overflow on the smartphone when the file upload is used.

Reproducible by adding an upload field to the form builder.

![form-overflow-03](https://github.com/soflyy/breakdance-bugs/assets/133856828/ba9588a8-85a5-41d6-8853-5fe159176be7)

**The solution:** 
Advanced > Wrapper > Layouts > Advanced > Overflow > Hidden

![form-overflow-01](https://github.com/soflyy/breakdance-bugs/assets/133856828/ce9ef9ec-d770-4930-88f5-8cdda8438c91)
![form-overflow-02](https://github.com/soflyy/breakdance-bugs/assets/133856828/57205014-dbc1-4d61-b538-fd2f595b081d)

**Comment by a-dubiel** [comment] 2023-05-17 15:06
Hey @codingharz can you paste your element here? I can't reproduce this.

**Comment by a-dubiel** [comment] 2023-05-22 16:24
@codingharz I was able to reproduce it. We are working on fixing this. Will update this thread when the fix is released. Thanks.

**Comment by a-dubiel** [comment] 2023-06-01 13:12
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.

**Closed by a-dubiel** 2023-06-01 13:12 UTC
Labels: :bug: bug, :rocket:    planned
