### ISSUE TITLE
No option to link post title to post url

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#216] opened 2022-08-12 19:02 UTC
Nice new loop builder, but i am missing some options that are available in the post list element. Like the option to link the post title element to the post url. WIth the post list element, the post title is linking to post url by default.

**Comment by etjallings** [comment] 2022-08-13 11:59
Beta 7 has a way to work around this with the option for dynamic link value to post permalink. But would be good to create a option to link the post title element to the post permalink.

**Comment by louisreingold** [comment] 2022-08-16 01:05
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/218.

**Closed by louisreingold** 2022-08-16 01:05 UTC
