### ISSUE TITLE
Shortcode element is not displaying correctly

### ISSUE THREAD

**Issue by alemacielsilva** [soflyy/breakdance-bugs#142] opened 2022-07-29 12:24 UTC
(RUNNING IN LOCALHOST) Just a detail, but apparently the Shortcode element is not displaying correctly in the constructor. But on the frontend it's ok.

https://user-images.githubusercontent.com/21241956/181757506-1de452f1-df19-4924-85f9-8c44bc23eb8c.mp4

![image](https://user-images.githubusercontent.com/21241956/181757688-1037bb7c-23d1-41e8-9773-cdf71c24b1d3.png)

**Comment by louisreingold** [comment] 2022-07-30 20:15
Thanks for the report. I'm closing this as it's not a bug in Breakdance. The shortcode requires scripts to be present but it's likely the plugin that provides the shortcode doesn't enqueue the scripts in such a way that they will be available in Breakdance's UI.

Ultimately, it works on the frontend, which is what matters.

**Closed by louisreingold** 2022-07-30 20:15 UTC
