### ISSUE TITLE
Invisible button to confirm a deletion

### ISSUE THREAD

**Issue by rbogdanowicz** [soflyy/breakdance-bugs#204] opened 2022-08-10 21:05 UTC
When deleting a typography preset the confirm button has the bg and color blank, correct the css to make it visible.

Screenshot:
![image](https://user-images.githubusercontent.com/2027191/184019629-6ca014a5-5401-4604-a1ec-430e7b84d3fe.png)

**Comment by louisreingold** [comment] 2022-08-10 23:33
@rbogdanowicz

What version? Beta 6?

**Comment by rbogdanowicz** [comment] 2022-08-11 00:09
> @rbogdanowicz
> 
> What version? Beta 6?

Yep, beta 6

**Comment by louisreingold** [comment] 2022-08-12 21:07
I wonder if toggling dark mode on and off would have an effect.

**Comment by louisreingold** [comment] 2022-08-21 05:35
I can't reproduce this and neither can anyone else, but we've received more than one report of it.

**Comment by louisreingold** [comment] 2022-08-21 05:36
@rbogdanowicz does this still happen for you with beta 9? If so, can you send your WP admin login details to support@breakdance.com so we can take a look?

**Comment by rbogdanowicz** [comment] 2022-08-21 20:14
![image](https://user-images.githubusercontent.com/2027191/185809080-34144d09-12bd-4b5e-990b-66f0e06636df.png)

Hello @louisreingold 
I installed beta 9, cleared the cache, did all the procedures and I still have the "invisible" confirm delete button.
I will forward the login details to support@breakdance.com 👍

**Comment by louisreingold** [comment] 2022-08-21 20:27
Thanks. Also... what browser / OS are you using?

**Comment by rbogdanowicz** [comment] 2022-08-21 20:29
> Thanks. Also... what browser / OS are you using?

Windows 11
Chrome 104.0.5112.81

**Comment by a-dubiel** [comment] 2022-11-26 12:38
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.

**Closed by a-dubiel** 2022-11-26 12:38 UTC
Labels: :art:  ui & ux
