### ISSUE TITLE
Adjacent Posts - previous label not positioned correctly

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#186] opened 2022-08-08 22:04 UTC
![Screen Shot 2022-08-08 at 17 20 40](https://user-images.githubusercontent.com/5446224/183522333-12043a3d-124e-4a68-ab5b-73a6c3f9ce65.png)

![Screen Shot 2022-08-08 at 17 20 58](https://user-images.githubusercontent.com/5446224/183522359-946f19a2-d01d-41be-a779-44c78ae6a199.png)

![Screen Shot 2022-08-08 at 18 01 57](https://user-images.githubusercontent.com/5446224/183522392-d4fae409-f177-4ee4-8a0b-1eca2841437b.png)

**Comment by louisreingold** [comment] 2022-08-11 03:27
I tried various combinations of the settings for this element and couldn't get it to appear like this.

Please either:
 - email support@breakdance.com with your WP admin login details and the page that has the problem
 - "export" and send me the element's settings using the following steps: https://www.loom.com/share/d72d241cfb5049c0a40c5c7b5e57fb46

**Comment by Anticosti** [comment] 2022-08-11 04:31
Logins sent.

**Comment by Spellhammer** [comment] 2022-08-11 12:41
This issue is caused by text-align: center being set on the containing section.

To reproduce:

1. In a Single Post template, add a Section and an Adjacent Posts element within that Section
2. On the Section, set Layout > Align to Center

You'll see that the left-hand label is now incorrectly positioned. This can be fixed by adding something like:
```
.ee-adjacentposts-prev .ee-adjacentposts-label {
text-align: left;
}
```

**Comment by louisreingold** [comment] 2022-08-12 09:53
This will be fixed in beta 7/8.

**Closed by louisreingold** 2022-08-12 09:53 UTC
