### ISSUE TITLE
Icons Disappear when creating a Design Preset on Advanced Accordion

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#1183] opened 2024-12-17 03:13 UTC
1) Add an Advanced Accordion to your page
2) Create a new Design Preset from the styles
3) Notice that the open / close icons disappear immediately after creating the preset.  I haven't figured out how to get them back even if I try editing the preset and changing the icons.

 - Breakdance Version 2.2.0

**Comment by breakdancemoderator** [comment] 2024-12-26 17:33
Duplicate of https://github.com/soflyy/breakdance-bugs/issues/1166

**Closed as completed by breakdancemoderator** 2024-12-26 17:33 UTC
Labels: :crossed_fingers: unconfirmed
