### ISSUE TITLE
RC 1 - Popups - Trigger on click not working.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#358] opened 2022-09-09 15:51 UTC
To reproduce:

1. Add a page, edit it in Breakdance
2. Add a button with an ID of #trigger_popup
3. Save and exit to WordPress
4. Create a Breakdance popup set to location > everywhere **and** trigger on click > selector > #trigger_popup
5. Make sure the popup has some content in it
6. Go to the page where the #trigger_popup button is and click it, nothing happens

**Comment by alpabuz** [comment] 2022-09-15 06:38
In fact, it is better to use the button settings to call the Popup. It's easier for the user.

![444](https://user-images.githubusercontent.com/14180450/190332019-756cb34d-20c9-41a3-838a-781d0b16d754.png)

A more advanced user just needs to specify the selector correctly. In this case, the correct selector would be:

`#trigger_popup > button`

The problem is related to the fact that the button has an extra wrapper, and the ID is assigned to this wrapper, not to the `button`. A trigger can only fire when the button is clicked, at least that's how it works here.

**Comment by emyerfo** [comment] 2022-10-20 00:12
I have the same issue. I tried calling the popup from the button as well to no avail. seems broken

**Comment by emyerfo** [comment] 2022-10-20 00:22
this is the error in the console: 
![rwzzo](https://user-images.githubusercontent.com/108147547/196828433-287cae0c-7a22-4ee5-96c6-6a33d031c2fa.jpg)

**Closed** 2023-06-01 13:21 UTC
Labels: :bug: bug, :rocket:    planned
